version: '3.3'
services:
  dev:
    image: foodswithjudes/dev
    volumes:
      - .:/src
      # Mount a volume over where containers are stored to allow overlayfs to work.
      # - tmp:/var/lib/containers
      # Bind in the docker daemon socket so the docker client can access it.
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    user: dev
    working_dir: /src
    hostname: dev
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  linuxsetup:
    build:
# volumes:
#   tmp: {}
