name: dev

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: Build the docker image
        run: |
          docker buildx build --load dev/ \
            --tag docker.pkg.github.com/$GITHUB_REPOSITORY/dev:$GITHUB_SHA \
            --tag docker.pkg.github.com/$GITHUB_REPOSITORY/dev:latest \

      - name: Publish the docker image
        if: github.ref == 'refs/heads/master'
        run: |
          echo "$GITHUB_TOKEN" | docker login -u "$GITHUB_ACTOR" --password-stdin
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dev:$GITHUB_SHA &
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dev:latest &
          wait
