name: dev

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: Build the docker image
        run: |
          # Login to this repo's Docker registry.
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login docker.pkg.github.com -u "x-access-token" --password-stdin

          # Calculate docker tags
          DOCKER_REPO="docker.pkg.github.com/$GITHUB_REPOSITORY/dev"
          # Coalesce the git ref into a valid docker tag by replacing '/'
          # with '_', replacing all other invalid characters with '-', and
          # truncating to 128 characters.
          REF_TAG="$(echo ${GITHUB_REF#"refs/heads/"} | tr '/', '_' | tr -c '[:alnum:]._-' '-' | cut -c 1-128)"

          # Build and push, only adding the latest tag for builds on master.
          docker buildx build . \
            --load \
            --tag "$DOCKER_REPO:$GITHUB_SHA" \
            --tag "$DOCKER_REPO:$REF_TAG" \
            $([ "$GITHUB_REF" = "refs/heads/master" ] && echo "--tag $DOCKER_REPO:latest" || echo "")
          docker push "$DOCKER_REPO:$GITHUB_SHA"
          docker push "$DOCKER_REPO:$REF_TAG"
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            docker push "$DOCKER_REPO:latest"
          fi
