name: dev

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: Build the docker image
        run: |
          docker buildx build --load . \
            --tag docker.pkg.github.com/$GITHUB_REPOSITORY/dev:$GITHUB_SHA \
            --tag docker.pkg.github.com/$GITHUB_REPOSITORY/dev:${GITHUB_REF#"refs/heads/"} \
            --tag docker.pkg.github.com/$GITHUB_REPOSITORY/dev:latest

      - name: Publish the docker image
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login -u "x-access-token" --password-stdin
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dev:$GITHUB_SHA &
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dev:${GITHUB_REF#"refs/heads/"} &
          # Only push the :latest tag for builds on master
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dev:latest &
          fi
          wait
