name: dev

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: Build the docker image
        run: |
          # Login to this repo's Docker registry.
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}' > /dev/null

          # Calculate docker tags
          DOCKER_REPO="foodswithjudes/dev"
          # Coalesce the git ref into a valid docker tag by removing newlines,
          # replacing '/' with '_', replacing all other invalid characters with
          # '-', and truncating to 128 characters.
          REF_TAG="$(echo ${GITHUB_REF#"refs/heads/"} | cut -c 1-128 | tr --delete '\n' | tr '/', '_' | tr -c '[:alnum:]._-' '-')"

          # Build and push, only adding the latest tag for builds on master.
          docker buildx build dev \
            --cache-from=foodswithjudes/dev:cache \
            --cache-to=foodswithjudes/dev:cache \
            --push \
            --tag "$DOCKER_REPO:$GITHUB_SHA" \
            --tag "$DOCKER_REPO:$REF_TAG" \
            $([ "$GITHUB_REF" = "refs/heads/master" ] && echo "--tag=$DOCKER_REPO:latest" || echo "")
